"""
Live AI Interpreter
-------------------
A real-time, asynchronous audio-processing desktop application.
It acts as a seamless bridge for cross-lingual communication, designed to capture 
live microphone input, translate it contextually, and output localized speech.

Architecture:
- Producer: A dedicated background thread capturing and slicing audio based on custom VAD thresholds.
- Consumer: An asynchronous pipeline handling ASR (GPU), Translation (Cloud), and TTS playback.
- UI: A responsive CustomTkinter interface running on the main thread.
"""

import os
import uuid
import queue
import logging
import asyncio
import threading
from typing import Optional, List

import numpy as np
import sounddevice as sd
from scipy.io.wavfile import write
import customtkinter as ctk
import pygame

# AI & Processing Pipelines
from faster_whisper import WhisperModel
from deep_translator import GoogleTranslator
import edge_tts

# -----------------------------------------------------------------------------
# System Configuration
# -----------------------------------------------------------------------------
class AppConfig:
    # Audio settings
    SAMPLE_RATE = 16000
    CHANNELS = 1
    DTYPE = 'int16'
    BLOCKSIZE = 1024
    
    # Anti-Hallucination & VAD (Voice Activity Detection) Matrix
    VOL_THRESHOLD = 700           # Hardware Filter: Ignores low room static
    MIN_DURATION_SEC = 0.5        # Ignores keyboard clacks and desk bumps
    SILENCE_TIMEOUT_SEC = 1.2     # Silence required to "slice" the sentence
    
    # AI Confidence Scoring
    WHISPER_CONFIDENCE_MIN = 0.6  # Drop text if no_speech_prob is higher than this
    
    # Language & Voice Mapping (Target Name -> (Translation Code, Edge-TTS Voice))
    LANGUAGES = {
        "Marathi": ("mr", "mr-IN-AarohiNeural"),
        "Bengali": ("bn", "bn-IN-TanishaaNeural"),
        "Telugu":  ("te", "te-IN-MohanNeural"),
        "Hindi":   ("hi", "hi-IN-SwaraNeural")
    }
    
    # Ghost phrases generated by Whisper during pure silence
    GHOST_PHRASES = {"Thank you", "Bye", "Bye bye", "I like it", "Yeah", "Okay", "Oh", "You"}

# -----------------------------------------------------------------------------
# Logging Setup
# -----------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s] [%(levelname)s] [%(threadName)s] %(message)s",
    datefmt="%H:%M:%S"
)
logger = logging.getLogger(__name__)

# -----------------------------------------------------------------------------
# Main Application Class
# -----------------------------------------------------------------------------
class InterpreterApp(ctk.CTk):
    def __init__(self):
        super().__init__()
        
        # 1. UI Initialization
        ctk.set_appearance_mode("System")
        ctk.set_default_color_theme("blue")
        self.title("Live AI Interpreter - Zero Latency Pipeline")
        self.geometry("850x500")
        
        self._setup_ui()
        
        # 2. State & Concurrency Management
        self.is_recording = False
        self.audio_queue: queue.Queue = queue.Queue()
        self.mic_thread: Optional[threading.Thread] = None
        self.ai_thread: Optional[threading.Thread] = None
        
        # 3. AI Model Initialization
        logger.info("Loading Faster-Whisper Model to VRAM... (Optimized for RTX 3050)")
        self.whisper_model = WhisperModel("base", device="cuda", compute_type="float16")
        
        # Initialize the invisible audio player for Virtual Audio Cable routing
        pygame.mixer.init()
        logger.info("System Ready. Awaiting user input.")

    def _setup_ui(self) -> None:
        """Constructs the thread-safe CustomTkinter interface."""
        self.grid_columnconfigure(0, weight=1)
        self.grid_columnconfigure(1, weight=1)
        self.grid_rowconfigure(0, weight=1)

        # English (Source) Textbox
        self.english_textbox = ctk.CTkTextbox(self, font=("Arial", 16), wrap="word")
        self.english_textbox.grid(row=0, column=0, padx=20, pady=20, sticky="nsew")
        self._update_text_safe(self.english_textbox, "Listening (English)...\n\nYour speech will appear here.")

        # Translated (Target) Textbox
        self.translated_textbox = ctk.CTkTextbox(self, font=("Arial", 16), wrap="word")
        self.translated_textbox.grid(row=0, column=1, padx=20, pady=20, sticky="nsew")
        self._update_text_safe(self.translated_textbox, "Translation...\n\nThe translated text will appear here.")

        # Control Panel
        self.control_frame = ctk.CTkFrame(self, fg_color="transparent")
        self.control_frame.grid(row=1, column=0, columnspan=2, pady=(0, 20))

        self.language_var = ctk.StringVar(value="Marathi")
        self.language_dropdown = ctk.CTkOptionMenu(
            self.control_frame, 
            values=list(AppConfig.LANGUAGES.keys()),
            variable=self.language_var,
            font=("Arial", 14)
        )
        self.language_dropdown.pack(side="left", padx=20)

        self.record_btn = ctk.CTkButton(
            self.control_frame, 
            text="Start Interpreter", 
            command=self.toggle_recording,
            font=("Arial", 14, "bold"),
            fg_color="green",
            hover_color="darkgreen"
        )
        self.record_btn.pack(side="left", padx=20)

    # --- UI THREAD-SAFE HELPERS ---
    def _update_text_safe(self, textbox: ctk.CTkTextbox, new_text: str) -> None:
        """Safely updates a disabled text box from background threads."""
        textbox.configure(state="normal")
        textbox.delete("0.0", "end")
        textbox.insert("0.0", new_text)
        textbox.configure(state="disabled")

    def toggle_recording(self) -> None:
        """Handles the Start/Stop state and spins up the Producer/Consumer threads."""
        if not self.is_recording:
            # Engage Pipeline
            self.is_recording = True
            self.record_btn.configure(text="Stop Interpreter", fg_color="red", hover_color="darkred")
            
            # Spawn isolated background workers to prevent UI freezing
            self.mic_thread = threading.Thread(target=self._microphone_producer, daemon=True, name="ProducerThread")
            self.ai_thread = threading.Thread(target=self._start_ai_consumer, daemon=True, name="ConsumerThread")
            
            self.mic_thread.start()
            self.ai_thread.start()
        else:
            # Shutdown Pipeline
            self.is_recording = False
            self.record_btn.configure(text="Start Interpreter", fg_color="green", hover_color="darkgreen")
            self._update_text_safe(self.english_textbox, "Stopped listening.\nPress Start to resume.")
            self._update_text_safe(self.translated_textbox, "System paused.")

    # ==========================================
    # THREAD 1: THE PRODUCER (Always Listening)
    # ==========================================
    def _microphone_producer(self) -> None:
        """
        Actively listens to the microphone, calculating rolling volume metrics.
        Slices audio chunks exactly when the user finishes speaking and queues them.
        """
        max_silence_chunks = int(AppConfig.SILENCE_TIMEOUT_SEC * (AppConfig.SAMPLE_RATE / AppConfig.BLOCKSIZE))
        min_speech_chunks = int(AppConfig.MIN_DURATION_SEC * (AppConfig.SAMPLE_RATE / AppConfig.BLOCKSIZE))

        q = queue.Queue()

        def audio_callback(indata, frames, time, status):
            """Catch stream data non-blockingly."""
            if status:
                logger.warning(f"Audio status: {status}")
            q.put(indata.copy())

        self.after(0, lambda: self._update_text_safe(self.english_textbox, "🟢 Mic open. Listening continuously..."))
        logger.info("Microphone Producer thread started.")

        with sd.InputStream(samplerate=AppConfig.SAMPLE_RATE, channels=AppConfig.CHANNELS, 
                            dtype=AppConfig.DTYPE, blocksize=AppConfig.BLOCKSIZE, callback=audio_callback):
            
            while self.is_recording:
                silence_counter = 0
                audio_data: List[np.ndarray] = []
                has_spoken = False
                
                # Buffer stream until silence is detected
                while self.is_recording:
                    try:
                        chunk = q.get(timeout=0.5) 
                    except queue.Empty:
                        continue

                    audio_data.append(chunk)
                    volume = np.linalg.norm(chunk)

                    if volume > AppConfig.VOL_THRESHOLD:
                        has_spoken = True
                        silence_counter = 0  # Reset silence timeout
                    elif has_spoken:
                        silence_counter += 1

                    if has_spoken and silence_counter > max_silence_chunks:
                        break # Sentence finished

                if not self.is_recording:
                    break
                    
                # The Fix: Duration Filter - require sustained audio to block desk bumps
                if len(audio_data) > min_speech_chunks and has_spoken:
                    # Use UUID for collision-proof temporary file naming
                    slice_filename = f"temp_mic_{uuid.uuid4().hex[:8]}.wav"
                    final_recording = np.concatenate(audio_data, axis=0)
                    write(slice_filename, AppConfig.SAMPLE_RATE, final_recording)
                    
                    self.audio_queue.put(slice_filename)
                    logger.info(f"Chunk finalized. Sent to AI Bridge: {slice_filename}")

    # ==========================================
    # THREAD 2: THE CONSUMER (Always Processing)
    # ==========================================
    def _start_ai_consumer(self) -> None:
        """Wrapper to start the asynchronous consumer loop in its own thread."""
        asyncio.run(self._ai_consumer_loop())

    async def _ai_consumer_loop(self) -> None:
        """
        The core multi-stage AI pipeline:
        1. Transcribes via local Whisper (GPU).
        2. Applies Anti-Hallucination rules.
        3. Fetches cloud translation via deep-translator.
        4. Generates and plays Edge-TTS audio.
        """
        loop = asyncio.get_running_loop()
        logger.info("AI Consumer pipeline active.")
        
        while self.is_recording:
            # 1. Thread-safe Queue Fetching (Offloaded to executor to prevent async loop freezing)
            try:
                mic_file = await loop.run_in_executor(None, self.audio_queue.get_nowait)
            except queue.Empty:
                await asyncio.sleep(0.1)
                continue

            output_audio = None

            try:
                # --- Stage 1: Transcription (Faster-Whisper on GPU) ---
                segments, info = await loop.run_in_executor(
                    None, lambda: list(self.whisper_model.transcribe(
                        mic_file, 
                        beam_size=5,
                        language="en",          # Force English to stop ambient language guessing
                        vad_filter=True,        # Silero VAD integration
                        vad_parameters=dict(min_silence_duration_ms=500),
                        condition_on_previous_text=False # Prevents looping hallucinations
                    ))
                )
                
                # Anti-Hallucination: Probability Scoring
                valid_text = [seg.text for seg in segments if seg.no_speech_prob < AppConfig.WHISPER_CONFIDENCE_MIN]
                english_text = " ".join(valid_text).strip()
            
                # Anti-Hallucination: Blacklist Filtering
                clean_text = english_text.replace(".", "").replace(",", "").strip()
                if len(clean_text) < 4 or clean_text in AppConfig.GHOST_PHRASES:
                    logger.debug(f"Blocked hallucination or short noise: '{english_text}'")
                    continue

                # Update UI safely
                self.after(0, lambda t=english_text: self._update_text_safe(self.english_textbox, t))
                logger.info(f"Transcribed: {english_text}")

                # --- Stage 2: Contextual Translation ---
                target_lang_name = self.language_var.get()
                lang_code, tts_voice = AppConfig.LANGUAGES.get(target_lang_name, AppConfig.LANGUAGES["Hindi"])

                # Offload network request
                translated_text = await loop.run_in_executor(
                    None, 
                    lambda: GoogleTranslator(source='en', target=lang_code).translate(english_text)
                )
                
                self.after(0, lambda c=translated_text: self._update_text_safe(self.translated_textbox, c))
                logger.info(f"Translated ({target_lang_name}): {translated_text}")

                # --- Stage 3: Text-to-Speech (Edge-TTS) ---
                if not translated_text or not translated_text.strip():
                    continue

                output_audio = f"temp_out_{uuid.uuid4().hex[:8]}.mp3"
                try:
                    communicate = edge_tts.Communicate(translated_text, tts_voice)
                    await communicate.save(output_audio)
                except Exception as tts_error:
                    logger.error(f"TTS Generation failed (Network issue?): {tts_error}")
                    continue # Pipeline survives network drops

                # --- Stage 4: Invisible Playback (Routed to Virtual Audio Cable) ---
                if os.path.exists(output_audio):
                    pygame.mixer.music.load(output_audio)
                    pygame.mixer.music.play()
                    
                    # Await playback completion non-blockingly
                    while pygame.mixer.music.get_busy():
                        await asyncio.sleep(0.05)
                    
                    pygame.mixer.music.unload()

            except Exception as e:
                logger.error(f"Error in consumer execution pipeline: {e}")
            finally:
                # --- Stage 5: Guaranteed Cleanup ---
                for file_path in [mic_file, output_audio]:
                    if file_path and os.path.exists(file_path):
                        try:
                            os.remove(file_path)
                        except Exception as cleanup_err:
                            logger.warning(f"Could not delete temp file {file_path}: {cleanup_err}")
                            
                self.audio_queue.task_done()


if __name__ == "__main__":
    app = InterpreterApp()
    app.mainloop()